version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.1-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - setup_remote_docker
      - run: 
          name: "Docker Login."
          command:
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: "Build docker and push to docker hub."
          command:
            docker build -t hemaphat/devops-node:latest . && 
            docker build -t hemaphat/devops-node:${CIRCLE_SHA1} . &&
            docker push hemaphat/devops-node:latest &&
            docker push hemaphat/devops-node:${CIRCLE_SHA1}
      - run:
          name: "Deploy in rancher"
          command: |
            docker run --rm -it \
              -e CATTLE_ACCESS_KEY="$ACCESS_KEY" \
              -e CATTLE_SECRET_KEY="$SECRET_KEY" \
              -e CATTLE_URL="$CATTLE_URL" \
              etlweather/gaucho upgrade $RANCHER_ID \
              --imageUuid 'docker:hemaphat/devops-node:latest' \
              --batch_size 3 --start_first \
              --auto_complete --timeout 600 \
              \
      - run: 
          name: "End of job."
          command:
            echo Done
